### ISSUE TITLE
initial setup fails with KeyError: 'activeAnimeDirectory'

### ISSUE THREAD

**Issue by scratchmex** [buildarr/buildarr-jellyseerr#23] opened 2024-02-05 21:30 UTC
jellyseer is already configured and when I add the following entry and start buildarr it fails. I feel because I don't have any anime related config set

```
# buildarr.yaml
jellyseerr:
  api_key: AbCdEfGhIjKlMnOpQrStUvWxYzaBcDeFgHiJkLmNoPqRsTuVwXyZ123456789012345=
```

```
buildarr  | 2024-02-05 21:26:46,568 buildarr:1 buildarr.cli.daemon [ERROR] <jellyseerr> (default) An error occurred while applying initial configuration: 'activeAnimeDirectory'
buildarr  | Traceback (most recent call last):
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
buildarr  |     run_apply()
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 235, in _run
buildarr  |     remote_instance_config = manager.from_remote(instance_config, instance_secrets)
buildarr  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
buildarr  |     return instance_config.from_remote(secrets)
buildarr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr_jellyseerr/config/__init__.py", line 177, in from_remote
buildarr  |     settings=JellyseerrSettings.from_remote(secrets),
buildarr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
buildarr  |     fields[field_name] = field.type_.from_remote(secrets)
buildarr  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
buildarr  |     fields[field_name] = field.type_.from_remote(secrets)
buildarr  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr_jellyseerr/config/settings/services/sonarr.py", line 514, in from_remote
buildarr  |     definitions={
buildarr  |                 ^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr_jellyseerr/config/settings/services/sonarr.py", line 515, in <dictcomp>
buildarr  |     api_service["name"]: Sonarr._from_remote(api_service)
buildarr  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr_jellyseerr/config/settings/services/sonarr.py", line 203, in _from_remote
buildarr  |     **cls.get_local_attrs(remote_map=cls._get_remote_map(), remote_attrs=remote_attrs),
buildarr  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
buildarr  |   File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 234, in get_local_attrs
buildarr  |     remote_attr = remote_attrs[remote_attr_name]
buildarr  |                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
buildarr  | KeyError: 'activeAnimeDirectory'
```

**Comment by Callum027** [comment] 2024-03-02 02:11
Hi @scratchmex, thank you for the bug report.

This is not necessarily because you don't have any anime-related configuration set (the plugin was designed to handle that case.) In this case Jellyseerr is not including `activeAnimeDirectory` in its API response, but Buildarr always expects it to be there, even if it is not used (just set to `null`).

I will create a patch to resolve this issue, which should be released later today.

**Comment by Callum027** [comment] 2024-03-02 03:56
Thanks for waiting. The fix for this issue has been released as:

* Docker Container: [`callum027/buildarr:0.7.6`](https://hub.docker.com/r/callum027/buildarr) (or update your local container if using `latest`)
* Windows Installer: [`buildarr-installer-0.7.6-x64.exe`](https://github.com/buildarr/buildarr-installer/releases/tag/v0.7.6)
* Python Package: [`buildarr-jellyseerr==0.3.2`](https://pypi.org/project/buildarr-jellyseerr/0.3.2)

Please give the new version a try to check that it resolves your issue.

**Comment by Callum027** [comment] 2024-04-27 00:58
The fix for this issue has been released for some time, so I am closing this issue.

Please let me know if you run into any additional problems, either relating to this issue or using Buildarr in general.

**Closed as completed by Callum027** 2024-04-27 00:58 UTC
Labels: bug
